### Obtener todos los usuarios 123
GET http://localhost:3000/api/users
Content-Type: application/json

### Crear un nuevo usuario
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Juan",
  "email": "juan@example.com"
}

### Actualizar un usuario
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
  "name": "Juan Actualizado"
}

### Eliminar un usuario
DELETE http://localhost:3000/api/users/1
