### Get all user
GET http://localhost:3000/api/user/getAll
Content-Type: application/json

### Get a user by ID
GET http://localhost:3000/api/user/getById/1
Content-Type: application/json

### Create a new user
POST http://localhost:3000/api/user/create
Content-Type: application/json

{
  "name": "Juan",
  "email": "juan@example.com"
}

### Update a user
PUT http://localhost:3000/api/user/update/1
Content-Type: application/json

{
  "name": "Juan Updated"
}

### Delete a user
DELETE http://localhost:3000/api/user/remove/1
Content-Type: application/json